package commands

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"

	"github.com/E3CNC/e3cnc/cli/go/internal/instance"
)

// ── detect-mcu ────────────────────────────────────────────────────

func cmdDetectMCU(jsonOut bool) bool {
	serialDir := "/dev/serial/by-id/"
	entries, err := os.ReadDir(serialDir)
	if err != nil {
		if jsonOut {
			printJSON(map[string]interface{}{"mcu": nil, "error": "no MCU detected"})
		} else {
			fmt.Println("  No MCU detected")
		}
		return true
	}

	var devices []string
	for _, entry := range entries {
		if entry.Type().IsRegular() || entry.Type()&os.ModeSymlink != 0 {
			devices = append(devices, entry.Name())
		}
	}

	if jsonOut {
		if len(devices) > 0 {
			printJSON(map[string]interface{}{"mcu": devices[0], "all": devices})
		} else {
			printJSON(map[string]interface{}{"mcu": nil})
		}
		return true
	}

	if len(devices) == 0 {
		fmt.Println("  No MCU detected")
		return true
	}
	for _, d := range devices {
		fmt.Printf("  %s\n", d)
	}
	return true
}

// ── init-config ───────────────────────────────────────────────────

func cmdInitConfig(jsonOut bool, args []string) bool {
	inst := resolveInstance(args)
	if inst == nil {
		fmt.Fprintln(os.Stderr, "  Error: no instance found")
		return true
	}

	mcuPath := ""
	entries, _ := os.ReadDir("/dev/serial/by-id/")
	if len(entries) > 0 {
		mcuPath = filepath.Join("/dev/serial/by-id/", entries[0].Name())
	}

	// Generate a basic CNC printer.cfg
	cfg := fmt.Sprintf(`# E3CNC CNC printer.cfg — generated by init-config
# Adjust the paths and parameters below for your machine.

[mcu]
serial: %s
# baud: 250000

[stepper_x]
step_pin: PA2
dir_pin: PA1
enable_pin: PA0
microsteps: 16
rotation_distance: 40
position_endstop: 0
position_min: 0
position_max: 300
homing_speed: 50

[stepper_y]
step_pin: PC7
dir_pin: PC6
enable_pin: PC5
microsteps: 16
rotation_distance: 40
position_endstop: 265
position_min: 0
position_max: 265
homing_speed: 50

[stepper_z]
step_pin: PB9
dir_pin: PB8
enable_pin: PB7
microsteps: 16
rotation_distance: 8
position_endstop: 0
position_min: -5
position_max: 250

# !!! ADJUST the above values for your machine !!!

[output_pin spindle]
pin: PB13
pwm: True
cycle_time: 0.100
hardware_pwm: False
scale: 100
value: 0

[heater_bed]
heater_pin: PB14
sensor_type: Generic 3950
sensor_pin: PK5
control: watermark
min_temp: 0
max_temp: 130

[temperature_sensor chamber]
sensor_type: Generic 3950
sensor_pin: PK6
min_temp: 0
max_temp: 100

[fan]
pin: PB15

[mcu rpi]
serial: /tmp/klipper_host_mcu.socket

[force_move]
enable_force_move: True

[printer]
kinematics: corexy
max_velocity: 300
max_accel: 3000
max_z_velocity: 20
max_z_accel: 100

[respond]
default_type: echo
default_prefix: "//"
`, mcuPath)

	os.MkdirAll(inst.ConfigDir, 0755)
	if err := os.WriteFile(inst.PrinterCfg, []byte(cfg), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "  Error writing config: %v\n", err)
		return true
	}

	fmt.Printf("  ✅ Config written to %s\n", inst.PrinterCfg)
	fmt.Println("  Search for '!!! ADJUST' in the file and update for your machine")
	return true
}

// ── restart ───────────────────────────────────────────────────────

func cmdRestart(jsonOut bool, args []string) bool {
	inst := resolveInstance(args)
	if inst == nil {
		fmt.Fprintln(os.Stderr, "  Error: no instance found")
		return true
	}

	// Try systemctl first, fall back to supervisorctl
	cmds := []string{
		fmt.Sprintf("systemctl restart %s", inst.MoonrakerService),
		fmt.Sprintf("supervisorctl restart %s", inst.MoonrakerService),
	}
	// Also try nginx restart
	cmds = append(cmds, "systemctl reload nginx 2>/dev/null || nginx -s reload 2>/dev/null || true")

	for _, c := range cmds {
		exec.Command("bash", "-c", c).Run()
	}

	if jsonOut {
		printJSON(map[string]string{"status": "restarted", "instance": inst.Name})
	} else {
		fmt.Println("  Services restarted")
	}
	return true
}

// ── flash-mcu ─────────────────────────────────────────────────────

var mcuPresets = []struct {
	Name        string
	Description string
	Controller  string
	Protocol    string
}{
	{"Octopus Pro (STM32F446)", "BigTreeTech Octopus Pro with STM32F446", "STM32F446", "usb"},
	{"Octopus (STM32F407)", "BigTreeTech Octopus with STM32F407", "STM32F407", "usb"},
	{"Manta M8P (STM32F407)", "BigTreeTech Manta M8P with STM32F407", "STM32F407", "usb"},
	{"SKR 1.4 Turbo (LPC1769)", "BigTreeTech SKR 1.4 Turbo", "LPC1769", "usb"},
	{"SKR 2 (STM32F407)", "BigTreeTech SKR 2 with STM32F407", "STM32F407", "usb"},
	{"SKR Mini E3 V3 (STM32G0B1)", "BigTreeTech SKR Mini E3 V3", "STM32G0B1", "usb"},
	{"SKR Pico (RP2040)", "BigTreeTech SKR Pico", "RP2040", "usb"},
	{"BTT CB1 (Allwinner H616)", "BigTreeTech CB1 (host MCU)", "H616", "linux"},
	{"Raspberry Pi (RP2040)", "Raspberry Pi Pico/RP2040 USB", "RP2040", "usb"},
	{"Custom", "Manual configuration", "", ""},
}

func cmdFlashMCU(jsonOut bool, args []string) bool {
	// Scan for connected devices
	serialDir := "/dev/serial/by-id/"
	entries, _ := os.ReadDir(serialDir)
	devices := []string{}
	for _, e := range entries {
		devices = append(devices, e.Name())
	}

	if jsonOut {
		printJSON(map[string]interface{}{
			"devices": devices,
			"presets": len(mcuPresets),
		})
		return true
	}

	if len(devices) > 0 {
		fmt.Println("  Connected devices:")
		for _, d := range devices {
			fmt.Printf("    %s\n", d)
		}
		fmt.Println()
	}

	fmt.Println("  MCU presets:")
	for i, p := range mcuPresets {
		fmt.Printf("    %2d. %s\n", i+1, p.Name)
		fmt.Printf("        %s\n", p.Description)
	}

	// Look for klipper source
	klipperDir := filepath.Join(instance.E3CNCHome(), "klipper")
	if _, err := os.Stat(filepath.Join(klipperDir, "klippy", "klippy.py")); err == nil {
		fmt.Printf("\n  Klipper source found at: %s\n", klipperDir)
		fmt.Println("  Run 'make menuconfig' then 'make flash' from the klipper directory")
	} else {
		fmt.Println("\n  Klipper source not found — install Klipper first")
	}
	return true
}
